[
    {"Mathis Neunzig": "ma"},
    {"Mathis Neunzig": "at"},
    {"Mathis Neunzig": "th"},
    {"Mathis Neunzig": "hi"},
    {"Mathis Neunzig": "is"},
    {"Mathis Neunzig": "s "},
    {"Mathis Neunzig": " n"},
    {"Mathis Neunzig": "ne"},
    {"Mathis Neunzig": "eu"},
    {"Mathis Neunzig": "un"},
    {"Mathis Neunzig": "nz"},
    {"Mathis Neunzig": "zi"},
    {"Mathis Neunzig": "ig"},
    {"Mannheim SAP SE": "ma"},
    {"Mannheim SAP SE": "an"},
    {"Mannheim SAP SE": "nn"},
    {"Mannheim SAP SE": "nh"},
    {"Mannheim SAP SE": "he"},
    {"Mannheim SAP SE": "ei"},
    {"Mannheim SAP SE": "im"},
    {"Mannheim SAP SE": "m "},
    {"Mannheim SAP SE": " s"},
    {"Mannheim SAP SE": "sa"},
    {"Mannheim SAP SE": "ap"},
    {"Mannheim SAP SE": "p "},
    {"Mannheim SAP SE": " s"},
    {"Mannheim SAP SE": "se"},   
]